In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Police Data.csv")
df.head()

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65535 entries, 0 to 65534
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65535 non-null  object
 1   stop_time           65535 non-null  object
 2   country_name        0 non-null      float64
 3   driver_gender       61474 non-null  object
 4   driver_age_raw      61481 non-null  float64
 5   driver_age          61228 non-null  float64
 6   driver_race         61475 non-null  object
 7   violation_raw       61475 non-null  object
 8   violation           61475 non-null  object
 9   search_conducted    65535 non-null  bool
 10  search_type         2479 non-null   object
 11  stop_outcome        61475 non-null  object
 12  is_arrested         61475 non-null  object
 13  stop_duration       61475 non-null  object
 14  drugs_related_stop  65535 non-null  bool
dtypes: bool(2), float64(3), object(10)
memory usage: 6.6+ MB

1) Instruction ( For Data Cleaning ) - Remove the column that only contains missing values.

In [5]:
df.drop('country_name', axis=1,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65535 entries, 0 to 65534
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65535 non-null  object
 1   stop_time           65535 non-null  object
 2   driver_gender       61474 non-null  object
 3   driver_age_raw      61481 non-null  float64
 4   driver_age          61228 non-null  float64
 5   driver_race         61475 non-null  object
 6   violation_raw       61475 non-null  object
 7   violation           61475 non-null  object
 8   search_conducted    65535 non-null  bool
 9   search_type         2479 non-null   object
 10  stop_outcome        61475 non-null  object
 11  is_arrested         61475 non-null  object
 12  stop_duration       61475 non-null  object
 13  drugs_related_stop  65535 non-null  bool
dtypes: bool(2), float64(2), object(10)
memory usage: 6.1+ MB

 For Speeding , were Men or Women stopped more often ?

In [6]:
df[df['violation'] == 'Speeding']['driver_gender'].value_counts()

driver_gender
M    25517
F    11686
Name: count, dtype: int64

 Does gender affect who gets searched during a stop ?

In [7]:
df.groupby('driver_gender').search_conducted.sum()

driver_gender
F     366
M    2113
Name: search_conducted, dtype: int64

In [8]:
df['driver_gender'].value_counts()

driver_gender
M    45164
F    16310
Name: count, dtype: int64

What is the mean stop_duration

In [9]:
df.describe()

       driver_age_raw    driver_age
count    61481.000000  61228.000000
mean      1967.791106     34.148984
std        121.050106     12.760710
min          0.000000     15.000000
25%       1965.000000     23.000000
50%       1978.000000     31.000000
75%       1985.000000     43.000000
max       8801.000000     88.000000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65535 entries, 0 to 65534
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65535 non-null  object
 1   stop_time           65535 non-null  object
 2   driver_gender       61474 non-null  object
 3   driver_age_raw      61481 non-null  float64
 4   driver_age          61228 non-null  float64
 5   driver_race         61475 non-null  object
 6   violation_raw       61475 non-null  object
 7   violation           61475 non-null  object
 8   search_conducted    65535 non-null  bool
 9   search_type         2479 non-null   object
 10  stop_outcome        61475 non-null  object
 11  is_arrested         61475 non-null  object
 12  stop_duration       61475 non-null  object
 13  drugs_related_stop  65535 non-null  bool
dtypes: bool(2), float64(2), object(10)
memory usage: 6.1+ MB

In [12]:
df['stop_duration'].value_counts()

stop_duration
0-15 Min     47379
16-30 Min    11448
30+ Min       2647
2                1
Name: count, dtype: int64

In [13]:
df['stop_duration'] = df['stop_duration'].map({'0-15 Min':7.5,'16-30 Min': 23 ,'30+ Min': 30})
df.describe()

       driver_age_raw    driver_age  stop_duration
count    61481.000000  61228.000000   61474.000000
mean      1967.791106     34.148984      11.355313
std        121.050106     12.760710       7.188638
min          0.000000     15.000000       7.500000
25%       1965.000000     23.000000       7.500000
50%       1978.000000     31.000000       7.500000
75%       1985.000000     43.000000       7.500000
max       8801.000000     88.000000      30.000000

Compare the age distributions for each violation.

In [14]:
df['violation'].value_counts()

violation
Speeding               37204
Moving violation       11926
Equipment               6516
Other                   3583
Registration/plates     2243
Seat belt                  3
Name: count, dtype: int64

In [16]:
df.groupby('violation')['driver_age'].describe()

,count,mean,std,min,25%,50%,75%,max
violation,,,,,,,,
Equipment,6507.0,31.682957,11.380671,16.0,23.0,28.0,39.0,81.0
Moving violation,11876.0,36.736443,13.258350,15.0,25.0,35.0,47.0,86.0
Other,3477.0,40.362381,12.754423,16.0,30.0,41.0,50.0,86.0
Registration/plates,2240.0,32.656696,11.150780,16.0,24.0,30.0,40.0,74.0
Seat belt,3.0,30.333333,10.214369,23.0,24.5,26.0,34.0,42.0
Speeding,37120.0,33.262581,12.615781,15.0,23.0,30.0,42.0,88.0